@startuml

package "node middleware"{
   [node]
}

package "server" as h{
[node] - [Jersey]: "token"

[hibernate] --> [mysql]
[Jersey] --> [hibernate]
}
package "content"{
 [Jersey] --> [jackrebbit]:RSA token
 [jackrebbit]
}
@enduml